### ISSUE TITLE
Unify gmsh import functionallity

### ISSUE THREAD

**Issue by masonamccallum** [jlchan/StartUpDG.jl#29]
Current Gmsh import functionality  is separated by Gmsh file format. To import Gmsh version 2.2 the function `readGmsh2D` is used and its counterpart for Gmsh version 4.1 is `readGmsh2D_v4`. The resolution to this issue is to implement a function `read_gmsh_2d` which will handle Gmsh file format differences. 

`(VX,VY),EToV, grouping = readGmsh2D_v4(filename::String, options::MeshImportOptions)`
`(VX,VY), EToV = readGmsh2D(filename::String)`

In order to add additional gmsh functionality more data should be returned from the read_gmsh_2d function. A possible solution would be to define a custom struct for GMSH outputs and customize iterate.
  
# possible new implementation
`gmsh_import_data = read_gmsh_2d(filename::String,options::MeshImportOptions)`

**Comment by jlchan** [comment]
Thanks @masonamccallum! We should probably also document the Gmsh parsing capabilities so that users are aware of the `grouping` argument. 

Note to self: we should move to `read_gmsh_2d` internally and deprecate `readGmsh2D*` in this next version.
