### ISSUE TITLE
Gmsh tests failing on Windows 10

### ISSUE THREAD

**Issue by cgt3** [jlchan/StartUpDG.jl#51]
`Gmsh` testset encounters the error:
```
Got exception outside of a @test
 IOError: unlink("stderr.txt"): resource busy or locked (EBUSY)
```
when run on a Windows 10 Enterprise. This error was encountered by another group [here.](https://discourse.julialang.org/t/ioerror-unlink-resource-busy-or-locked-ebusy-in-windows/32045)

**Comment by jlchan** [comment]
@masonamccallum I think this is due to the output of your tests being piped to stderr.txt. Would you mind seeing if that can be removed? You should be able to save the outfit stream and manipulate it directly and Julia.

**Comment by jlchan** [comment]
Thank you for the PR! I think it's easy to add another platform - let me look into that later today (giving a seminar now)

**Comment by jlchan** [comment]
I updated ci.yml; let me see if this works for your PR

**Comment by jlchan** [comment]
After a few tries on the CI, looks like it works and runs windows x64 now! Thanks again @masonamccallum for the quick fix, and @cgt3 for catching this.
